# See <https://www.ruby-forum.com/t/forcing-stdout-sync-for-scripts/48876/8>
# #Project 3
#Yu Luna    yuki.coco@csu.fullerton.edu
#Tevin Vu   tuanvu01@csu.fullerton.edu
#Usage:     foreman start

alice_ts: ruby -e '$stdout.sync = true; load($0 = ARGV.shift)' tuplespace.rb -c alice.yaml
alice_adapter: ruby -e '$stdout.sync = true; load($0 = ARGV.shift)' adapter.rb -c alice.yaml
bob_ts: ruby -e '$stdout.sync = true; load($0 = ARGV.shift)' tuplespace.rb -c bob.yaml
bob_adapter: ruby -e '$stdout.sync = true; load($0 = ARGV.shift)' adapter.rb -c bob.yaml
chuck_ts: ruby -e '$stdout.sync = true; load($0 = ARGV.shift)' tuplespace.rb -c chuck.yaml
chuck_adapter: ruby -e '$stdout.sync = true; load($0 = ARGV.shift)' adapter.rb -c chuck.yaml